service: serverless-lambda-chrome
frameworkVersion: "1.72.0"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev
  profile: default
  environment:
    IS_OFFLINE: ${opt:offline}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
plugins:
  - serverless-webpack
#  - serverless-domain-manager
  - serverless-offline

layers:
  HeadlessChrome:
    name: HeadlessChrome
    compatibleRuntimes:
      - nodejs10.x
    description: Required for headless chrome
    package:
      artifact: layers/chrome_aws_lambda.zip
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - chrome-aws-lambda
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

 # customDomain:
 #   domainName: labs.mianio.com
 #   basePath: demo
 #   stage: ${self:provider.stage}
 #   createRoute53Record: true

functions:
  export-get:
#    provisionedConcurrency: 2
    handler: functions/export.generate
    layers:
      - { Ref: HeadlessChromeLambdaLayer }
    events:
      - http:
          path: export
          method: get
          cors: true
  
  export-post:
#    provisionedConcurrency: 2
    handler: functions/export.generate
    layers:
      - { Ref: HeadlessChromeLambdaLayer }
    events:
      - http:
          path: export
          method: post
          cors: true
          